##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  archlinux:
    # Useful URL: https://git.archlinux.org/svntogit/community.git/tree/mozo
    - gcc
    - git
    - gtk3
    - intltool
    - make
    - mate-common
    - mate-menus
    - meson
    - python-gobject
    - which

  debian:
    # Useful URL: https://github.com/mate-desktop/debian-packages
    # Useful URL: https://salsa.debian.org/debian-mate-team/mozo
    - autopoint
    - gettext
    - git
    - intltool
    - libmate-menu-dev
    - make
    - mate-common
    - meson
    - python-gi-dev
    - python3

  fedora:
    # Useful URL: https://src.fedoraproject.org/cgit/rpms/mozo.git
    - desktop-file-utils
    - gcc
    - git
    - make
    - mate-common
    - mate-menus-devel
    - meson
    - pygobject3-devel
    - python3-devel
    - redhat-rpm-config

  ubuntu:
    - autopoint
    - gettext
    - git
    - intltool
    - libmate-menu-dev
    - make
    - mate-common
    - meson
    - python-gi-dev
    - python3

variables:
  - CFLAGS="-Wall -Werror=format-security"

build_scripts:
  - NOCONFIGURE=1 ./autogen.sh
  - ./configure
  - make

after_scripts:
  - if [ ${BUILD_TYPE} == "scripts" ];then
  -     make distcheck
  - fi

releases:
  draft: false
  prerelease: false
  checksum: true
  file_glob: true
  files: mozo-*.tar.xz
  github_release:
    tags: true
    overwrite: true
    base_version: 1.20.0
    notify_servers:
      - https://release.mate-desktop.org/release
