.\" Man page for Mozo
.TH MOZO 1 "5 February 2014" "MATE Desktop Environment" "General Manual"
.\" Please adjust this date when revising the manpage.
.SH "NAME"
Mozo \- MATE Menu Editor
.SH "SYNOPSIS"
.B mozo
.SH "DESCRIPTION"
Mozo is a menu editor for MATE using the freedesktop.org menu specification. It is a fork of Alacarte.
.SH "BUGS"
.SS Should you encounter any bugs, they may be reported at: 
http://github.com/mate-desktop/mozo/issues
.SH "AUTHORS"
.SS Mozo is maintained by:
.nf
Perberos <perberos@gmail.com>
Steve Zesch <stevezesch2@gmail.com>
Stefano Karapetsas <stefano@karapetsas.com>
.fi
.PP
.SS This Manual Page has been written for the MATE Desktop Environment by:
Adam Erdman <hekel@archlinux.info> (2014)
.SH "HISTORY"
.SS Alacarte was written by Travis Watkins. <alleykat@gmail.com>
.SH "SEE ALSO"
.SS Mozo documentation can be found by pressing the F1 key. 
Further information may also be available at: http://wiki.mate-desktop.org/docs
